-- 从 6-10数据.xlsx 导入公出日志
-- 生成时间: 2026-06-11 15:42:08
-- 导入: 42 条, 匹配用户: 3, 未匹配: 40, 跳过重复: 1
USE wx_app_oa;

INSERT INTO daily_reports (report_date, initial_biz_trip_date, entry_date, project, area, related_party, workers, machine_model, work_content, required_qty, completed_qty, progress_percent, remark, today_work, today_work_type, tomorrow_work_type, biz_trip_days, personal_biz_trip_days, user_id, status, timeliness) VALUES ('2026-06-08', '2026-02-25', '2026-02-24', 'M7-E(10-233)内部客户内蒙古锡林郭勒盟苏尼特左旗风u电治沙项目250MW-25台-锡盟基地', '宁夏自治区中卫市', '浙江贝良', '李余伟', 'MySE233', '叶根载荷安装', 10, 10, 1.0, '套号D71FM26010 编号D71FM26C016 D71FM26D015', '传感器安装', '工作', '工作', 103, 104, NULL, 'submitted', 'on_time');
INSERT INTO daily_reports (report_date, initial_biz_trip_date, entry_date, project, area, related_party, workers, machine_model, work_content, required_qty, completed_qty, progress_percent, remark, today_work, today_work_type, tomorrow_work_type, biz_trip_days, personal_biz_trip_days, user_id, status, timeliness) VALUES ('2026-06-08', '2026-05-26', '2026-03-29', '福建莆田三峡平海湾DE区海上风电场', '福建莆田', '浙江贝良 北京拓维', '仪如招  李鑫', 'GW122', '叶片载荷传感器消缺', 12, 2, 0.1667, '今日海上雷雨大风，未安排出海作业。', '大风天气，未安排工作', '待工', '待工', 13, 71, NULL, 'submitted', 'on_time');
INSERT INTO daily_reports (report_date, initial_biz_trip_date, entry_date, project, area, related_party, workers, machine_model, work_content, required_qty, completed_qty, progress_percent, remark, today_work, today_work_type, tomorrow_work_type, biz_trip_days, personal_biz_trip_days, user_id, status, timeliness) VALUES ('2026-06-08', '2026-03-04', '2026-03-04', '广东阳江中广核帆石二海上风电场/广东阳江三山岛六海上风电场', '广东阳江', '浙江贝良', '吕衎，王帅', '', '7台机组光纤载荷故障处理', 7, 3, 0.4286, '等待项目出海通知', '等待项目出海通知', '待工', '待工', 96, 96, NULL, 'submitted', 'on_time');
INSERT INTO daily_reports (report_date, initial_biz_trip_date, entry_date, project, area, related_party, workers, machine_model, work_content, required_qty, completed_qty, progress_percent, remark, today_work, today_work_type, tomorrow_work_type, biz_trip_days, personal_biz_trip_days, user_id, status, timeliness) VALUES ('2026-06-08', NULL, '2026-05-20', '承德天润丰宁集中式300.00MW风电场', '河北省承德市丰宁县鱼儿山镇', '浙江贝良', '安义、李自阳（鑫凯）', '93A', '压电消缺', 3, 0, 0.0, '1.等待第三方人员到场', '1.办理入场', '在途', '在途', 0, 19, NULL, 'submitted', 'on_time');
INSERT INTO daily_reports (report_date, initial_biz_trip_date, entry_date, project, area, related_party, workers, machine_model, work_content, required_qty, completed_qty, progress_percent, remark, today_work, today_work_type, tomorrow_work_type, biz_trip_days, personal_biz_trip_days, user_id, status, timeliness) VALUES ('2026-06-08', '2026-05-27', '2026-03-04', '广西百色板桃国家电投风电场', '广西百色田林', '浙江贝良，北京拓维', '张云峰，韦少校', '', '板桃国家电投4台机组载荷振动传感器安装调试', 0, 1, NULL, '今日早上九米风速业主未开票', '振动载荷传感器安装', '待工', '工作', 12, 96, NULL, 'submitted', 'on_time');
INSERT INTO daily_reports (report_date, initial_biz_trip_date, entry_date, project, area, related_party, workers, machine_model, work_content, required_qty, completed_qty, progress_percent, remark, today_work, today_work_type, tomorrow_work_type, biz_trip_days, personal_biz_trip_days, user_id, status, timeliness) VALUES ('2026-06-08', '2026-06-05', '2026-03-04', 'MySE18-292中广核广东阳江帆石二1000MW一标段【三标段】（中标600MW）', '陆丰市 明阳叶片厂', '浙江贝良，北京拓维', '吴育庆，候明泽', 'MY143', '安装载荷传感器', 0, 0, NULL, '大雨天气，未作业', '传感器安装', '待工', '工作', 3, 96, NULL, 'submitted', 'on_time');
INSERT INTO daily_reports (report_date, initial_biz_trip_date, entry_date, project, area, related_party, workers, machine_model, work_content, required_qty, completed_qty, progress_percent, remark, today_work, today_work_type, tomorrow_work_type, biz_trip_days, personal_biz_trip_days, user_id, status, timeliness) VALUES ('2026-06-08', '2026-06-05', '2026-06-04', '明阳国电投巨鹿ipc项目', '河北省邢台市巨鹿县', '浙江贝良', '王腾', 'MySE200', 'ipc故障消缺', 16, 2, 0.125, '1.排查12# 号风机，数据正常，没问题 2.更换10# 风机叶片三跳线，数据恢复正常，并网后又报警，导出秒级数据，发技术人员分析', 'ipc故障排查处理', '工作', '工作', 3, 4, NULL, 'submitted', 'on_time');
INSERT INTO daily_reports (report_date, initial_biz_trip_date, entry_date, project, area, related_party, workers, machine_model, work_content, required_qty, completed_qty, progress_percent, remark, today_work, today_work_type, tomorrow_work_type, biz_trip_days, personal_biz_trip_days, user_id, status, timeliness) VALUES ('2026-06-08', '2026-05-19', '2026-03-04', '南非Beta-2项目', '江苏省扬州市扬州港', '浙江贝良、北京拓维', '田子民、孙润耕', 'SI90.2', '叶根载荷+光纤振动安装', 3, 2, 0.6667, '套号', 'ZC1S190.2C26059 叶根载荷+振动传感器安装', '工作', '工作', 20, 96, NULL, 'submitted', 'on_time');
INSERT INTO daily_reports (report_date, initial_biz_trip_date, entry_date, project, area, related_party, workers, machine_model, work_content, required_qty, completed_qty, progress_percent, remark, today_work, today_work_type, tomorrow_work_type, biz_trip_days, personal_biz_trip_days, user_id, status, timeliness) VALUES ('2026-06-08', '2026-05-19', '2026-03-04', '埃及Ras Ghareb-1项目', '江苏省扬州市扬州港', '浙江贝良、北京拓维', '田子民、孙润耕', 'SI90.2', '叶根载荷+光纤振动安装', 2, 1, 0.5, '套号', 'ZC1S190.2C26046 叶根载荷+振动传感器安装', '工作', '工作', 20, 96, NULL, 'submitted', 'on_time');
INSERT INTO daily_reports (report_date, initial_biz_trip_date, entry_date, project, area, related_party, workers, machine_model, work_content, required_qty, completed_qty, progress_percent, remark, today_work, today_work_type, tomorrow_work_type, biz_trip_days, personal_biz_trip_days, user_id, status, timeliness) VALUES ('2026-06-08', '2026-04-10', '2026-04-10', '安徽亳州蒙城县坛城华润风电场', '安徽省亳州市坛城县', '浙江贝良，甘肃鑫凯', '徐羚译，李智文，田琳进，马延伟，郭俊峰，马金鹏', 'GW H191/5270（V12）', '叶片载荷，振动传感器消缺', 19, 19, 1.0, '1.完成A15号机组载荷DP线，电源线，接地线布线整改。 2..完成A07号机组载荷DP线，电源线，接地线布线整改。 3.完成A09号机组载荷控制柜内部件排查更换。压电传感器信号排查，压电控制柜内采集单元更换。', '1.根据风况开展作业。', '工作', '工作', 59, 59, NULL, 'submitted', 'on_time');
INSERT INTO daily_reports (report_date, initial_biz_trip_date, entry_date, project, area, related_party, workers, machine_model, work_content, required_qty, completed_qty, progress_percent, remark, today_work, today_work_type, tomorrow_work_type, biz_trip_days, personal_biz_trip_days, user_id, status, timeliness) VALUES ('2026-06-07', '2026-06-01', '2026-06-01', 'MYSE.5-216华电云南红河开远大黑山风电场扩建项目195MW', '云南省大理市宾川县', '浙江贝良', '罗宝山', 'MySE216', '叶根载荷安装', 3, 2, 0.6667, '套号', 'C79YM26A005 载荷传感器安装', '工作', '工作', 6, 6, NULL, 'submitted', 'on_time');
INSERT INTO daily_reports (report_date, initial_biz_trip_date, entry_date, project, area, related_party, workers, machine_model, work_content, required_qty, completed_qty, progress_percent, remark, today_work, today_work_type, tomorrow_work_type, biz_trip_days, personal_biz_trip_days, user_id, status, timeliness) VALUES ('2026-06-08', '2026-06-01', '2026-06-01', 'MYSE.5-216华电云南红河开远大黑山风电场扩建项目195MW', '云南省大理市宾川县', '浙江贝良', '罗宝山', 'MySE216', '叶根载荷安装', 3, 2, 0.6667, '叶片维修，未作业', '传感器安装', '待工', '工作', 7, 7, NULL, 'submitted', 'on_time');
INSERT INTO daily_reports (report_date, initial_biz_trip_date, entry_date, project, area, related_party, workers, machine_model, work_content, required_qty, completed_qty, progress_percent, remark, today_work, today_work_type, tomorrow_work_type, biz_trip_days, personal_biz_trip_days, user_id, status, timeliness) VALUES ('2026-06-08', '2026-05-30', '2026-03-05', '华电贵州黔西南州岩架风电场一期90MW', '贵州省黔西南州', '浙江贝良', '周洁/高裕', '', '激光雷达消缺', 0, 0, NULL, '1.远程协助阿荣旗激光雷达标定工作； 2.跟催中车横立山项目主控程序事宜； 3.高裕-乐清-册亨县，已到场', '1.激光雷达程序升级，安装消缺', '待工', '工作', 9, 95, 9, 'submitted', 'on_time');
INSERT INTO daily_reports (report_date, initial_biz_trip_date, entry_date, project, area, related_party, workers, machine_model, work_content, required_qty, completed_qty, progress_percent, remark, today_work, today_work_type, tomorrow_work_type, biz_trip_days, personal_biz_trip_days, user_id, status, timeliness) VALUES ('2026-06-08', '2026-05-25', '2026-03-04', '广东阳江市三山岛三海上国家电投一期风电场一标段', '阳江市平岗镇', '浙江贝良 北京拓维', '韩拥华   张泽源', 'GW130', '安装载荷，振动传感器', 0, 3, NULL, 'ZC10GW13026020套号 ZC10GW130260C15编号', '传感器安装', '工作', '工作', 14, 96, NULL, 'submitted', 'on_time');
INSERT INTO daily_reports (report_date, initial_biz_trip_date, entry_date, project, area, related_party, workers, machine_model, work_content, required_qty, completed_qty, progress_percent, remark, today_work, today_work_type, tomorrow_work_type, biz_trip_days, personal_biz_trip_days, user_id, status, timeliness) VALUES ('2026-06-09', '2026-05-19', '2026-03-04', '埃及Ras Ghareb-1项目', '江苏省扬州市扬州港', '浙江贝良、北京拓维', '田子民、孙润耕', 'SI90.2', '叶根载荷+光纤振动安装', 2, 2, 1.0, '套号', 'ZC1S190.2A26041 ZC1S190.2F26035 叶根载荷+振动传感器安装', '工作', '工作', 21, 97, NULL, 'submitted', 'on_time');
INSERT INTO daily_reports (report_date, initial_biz_trip_date, entry_date, project, area, related_party, workers, machine_model, work_content, required_qty, completed_qty, progress_percent, remark, today_work, today_work_type, tomorrow_work_type, biz_trip_days, personal_biz_trip_days, user_id, status, timeliness) VALUES ('2026-06-09', '2026-05-30', '2026-03-05', '华电贵州黔西南州岩架风电场一期90MW', '贵州省黔西南州', '浙江贝良', '周洁/高裕', '', '激光雷达消缺', 0, 0, NULL, '1.大同天镇项目毫米波净空程序升级工作，完成4台，累计完成16台； 2.明阳岩架1号风机激光雷达程序升级和角度调整，因雷雨天气未完成； 3.参加明阳山东半岛雷达样机挂机培训；', '1.激光雷达程序升级，安装消缺', '工作', '工作', 10, 96, 9, 'submitted', 'on_time');
INSERT INTO daily_reports (report_date, initial_biz_trip_date, entry_date, project, area, related_party, workers, machine_model, work_content, required_qty, completed_qty, progress_percent, remark, today_work, today_work_type, tomorrow_work_type, biz_trip_days, personal_biz_trip_days, user_id, status, timeliness) VALUES ('2026-06-09', '2026-03-04', '2026-03-04', '广东阳江中广核帆石二海上风电场/广东阳江三山岛六海上风电场', '广东阳江', '浙江贝良', '吕衎，王帅', '', '7台机组光纤载荷故障处理', 7, 3, 0.4286, '参加出海前班会', '出海，载荷振动传感器安装', '待工', '工作', 97, 97, NULL, 'submitted', 'on_time');
INSERT INTO daily_reports (report_date, initial_biz_trip_date, entry_date, project, area, related_party, workers, machine_model, work_content, required_qty, completed_qty, progress_percent, remark, today_work, today_work_type, tomorrow_work_type, biz_trip_days, personal_biz_trip_days, user_id, status, timeliness) VALUES ('2026-06-09', '2026-06-05', '2026-06-04', '明阳国电投巨鹿ipc项目', '河北省邢台市巨鹿县', '浙江贝良', '王腾', 'MySE200', 'ipc故障消缺', 16, 4, 0.25, '1.14# 号风机，1号叶片通道3无波长，经排查，跳线端损坏，更换跳线，数据恢复，光能量普遍偏低，但主控未报故障，尝试用新的跳线和载荷，依然偏低，技术人员反馈未报故障暂时不用更换解调仪 2.6#号 风机报载荷超限故障，上机排查通道2、4光能量低，清理插头重新拔插，数据恢复，待运行观察', 'ipc故障排查', '工作', '工作', 4, 5, NULL, 'submitted', 'on_time');
INSERT INTO daily_reports (report_date, initial_biz_trip_date, entry_date, project, area, related_party, workers, machine_model, work_content, required_qty, completed_qty, progress_percent, remark, today_work, today_work_type, tomorrow_work_type, biz_trip_days, personal_biz_trip_days, user_id, status, timeliness) VALUES ('2026-06-09', '2026-06-05', '2026-03-04', 'MySE18-292中广核广东阳江帆石二1000MW一标段【三标段】（中标600MW）', '陆丰市 明阳叶片厂', '浙江贝良，北京拓维', '吴育庆，候明泽', 'MY143', '安装载荷传感器', 0, 0, NULL, 'F11BM26019套号 F11BM26B022编号 F11BM26A025', '传感器安装', '工作', '工作', 4, 97, NULL, 'submitted', 'on_time');
INSERT INTO daily_reports (report_date, initial_biz_trip_date, entry_date, project, area, related_party, workers, machine_model, work_content, required_qty, completed_qty, progress_percent, remark, today_work, today_work_type, tomorrow_work_type, biz_trip_days, personal_biz_trip_days, user_id, status, timeliness) VALUES ('2026-06-09', '2026-05-26', '2026-03-29', '福建莆田三峡平海湾DE区海上风电场', '福建莆田', '浙江贝良 北京拓维', '仪如招  李鑫', 'GW122', '叶片载荷传感器消缺', 12, 2, 0.1667, '1.大风天气，未安排工作。 2.审核安装报告。', '大风天气，海况差。未安排工作', '待工', '待工', 14, 72, NULL, 'submitted', 'on_time');
INSERT INTO daily_reports (report_date, initial_biz_trip_date, entry_date, project, area, related_party, workers, machine_model, work_content, required_qty, completed_qty, progress_percent, remark, today_work, today_work_type, tomorrow_work_type, biz_trip_days, personal_biz_trip_days, user_id, status, timeliness) VALUES ('2026-06-09', '2026-02-25', '2026-02-24', 'M7-E(10-233)内部客户内蒙古锡林郭勒盟苏尼特左旗风u电治沙项目250MW-25台-锡盟基地', '宁夏自治区中卫市', '浙江贝良', '李余伟', 'MySE233', '叶根载荷安装', 14, 10, 0.7143, '套号D71FM26011 编号D71FM26D014', '传感器安装', '工作', '工作', 104, 105, NULL, 'submitted', 'on_time');
INSERT INTO daily_reports (report_date, initial_biz_trip_date, entry_date, project, area, related_party, workers, machine_model, work_content, required_qty, completed_qty, progress_percent, remark, today_work, today_work_type, tomorrow_work_type, biz_trip_days, personal_biz_trip_days, user_id, status, timeliness) VALUES ('2026-06-08', '2026-06-05', '2026-02-27', '重能新疆天山北麓新能源基地一标段项目', '新疆哈密淖毛湖', '浙江贝良，甘肃鑫凯', '薛森虎，张磊磊', 'V17，金风', 'G522机组2号叶片安装叶片载荷传感器', 0, 0, NULL, '1.金风天山北麓重能项目B522安装光纤载荷跳线及调试', '1.明阳华电新疆哈密天山北麓基地610万千瓦新能源420万项目标段四60万IPC辅控调试', '工作', '工作', 3, 101, NULL, 'submitted', 'on_time');
INSERT INTO daily_reports (report_date, initial_biz_trip_date, entry_date, project, area, related_party, workers, machine_model, work_content, required_qty, completed_qty, progress_percent, remark, today_work, today_work_type, tomorrow_work_type, biz_trip_days, personal_biz_trip_days, user_id, status, timeliness) VALUES ('2026-06-09', '2026-04-08', '2026-02-27', '华电新疆哈密天山北麓基地610万千瓦新能源420万项目标段四60万', '新疆哈密淖毛湖', '浙江贝良，甘肃鑫凯', '薛森虎，张磊磊', 'MySE11D233H125，明阳', '辅控叶片应力模块调试、一台机组IPC主控及辅控安装', 55, 0, 0.0, '1.到达场站后被通知大风，未作业', '1.IPC辅控调试', '工作', '工作', 62, 102, NULL, 'submitted', 'on_time');
INSERT INTO daily_reports (report_date, initial_biz_trip_date, entry_date, project, area, related_party, workers, machine_model, work_content, required_qty, completed_qty, progress_percent, remark, today_work, today_work_type, tomorrow_work_type, biz_trip_days, personal_biz_trip_days, user_id, status, timeliness) VALUES ('2026-06-09', '2026-05-27', '2026-03-04', '广西百色板桃国家电投风电场', '广西百色田林', '浙江贝良，北京拓维', '张云峰，韦少校', '', '板桃国家电投4台机组载荷振动传感器安装调试', 0, 1, NULL, '大风天气未作业', '振动载荷传感器安装（已经和现场确认明天可以作业）', '待工', '工作', 13, 97, NULL, 'submitted', 'on_time');
INSERT INTO daily_reports (report_date, initial_biz_trip_date, entry_date, project, area, related_party, workers, machine_model, work_content, required_qty, completed_qty, progress_percent, remark, today_work, today_work_type, tomorrow_work_type, biz_trip_days, personal_biz_trip_days, user_id, status, timeliness) VALUES ('2026-06-09', '2026-06-09', '2026-05-20', '承德天润丰宁集中式300.00MW风电场', '河北省承德市丰宁县鱼儿山镇', '浙江贝良', '安义、李自阳（鑫凯）', '93A', '压电消缺', 3, 0, 0.0, '1.办理入场，整理物料', '1.开展作业', '在途', '在途', 0, 20, NULL, 'submitted', 'on_time');
INSERT INTO daily_reports (report_date, initial_biz_trip_date, entry_date, project, area, related_party, workers, machine_model, work_content, required_qty, completed_qty, progress_percent, remark, today_work, today_work_type, tomorrow_work_type, biz_trip_days, personal_biz_trip_days, user_id, status, timeliness) VALUES ('2026-06-09', '2026-05-25', '2026-03-04', '广东阳江市三山岛三海上国家电投一期风电场一标段', '阳江市平岗镇', '浙江贝良 北京拓维', '韩拥华   张泽源', 'GW130', '安装载荷，振动传感器', 0, 3, NULL, 'ZC10GW13026021套号 ZC10GW130260B26020编号 载荷+振动', '传感器安装', '工作', '工作', 15, 97, NULL, 'submitted', 'on_time');
INSERT INTO daily_reports (report_date, initial_biz_trip_date, entry_date, project, area, related_party, workers, machine_model, work_content, required_qty, completed_qty, progress_percent, remark, today_work, today_work_type, tomorrow_work_type, biz_trip_days, personal_biz_trip_days, user_id, status, timeliness) VALUES ('2026-06-09', '2026-04-10', '2026-04-10', '安徽亳州蒙城县坛城华润风电场', '安徽省亳州市坛城县', '浙江贝良，甘肃鑫凯', '徐羚译，李智文', 'GW H191/5270（V12）', '叶片载荷，振动传感器消缺', 19, 19, 1.0, '1.该项目载荷控制柜DP布线整改已完成，人员田琳进，马延伟，郭俊峰，马金鹏已撤场 2.联系余肇鸿核对压电传感器信号异常机组，进行压电传感器消缺', '1.根据风况开展作业。', '待工', '工作', 60, 60, NULL, 'submitted', 'on_time');
INSERT INTO daily_reports (report_date, initial_biz_trip_date, entry_date, project, area, related_party, workers, machine_model, work_content, required_qty, completed_qty, progress_percent, remark, today_work, today_work_type, tomorrow_work_type, biz_trip_days, personal_biz_trip_days, user_id, status, timeliness) VALUES ('2026-06-09', '2026-06-01', '2026-06-01', 'MYSE.5-216华电云南红河开远大黑山风电场扩建项目195MW', '云南省大理市宾川县', '浙江贝良', '罗宝山', 'MySE216', '叶根载荷安装', 13, 2, 0.1538, '套号', 'C79YM26B008 载荷传感器安装', '工作', '工作', 8, 8, NULL, 'submitted', 'on_time');
INSERT INTO daily_reports (report_date, initial_biz_trip_date, entry_date, project, area, related_party, workers, machine_model, work_content, required_qty, completed_qty, progress_percent, remark, today_work, today_work_type, tomorrow_work_type, biz_trip_days, personal_biz_trip_days, user_id, status, timeliness) VALUES ('2026-06-10', '2026-06-01', '2026-06-01', 'MYSE.5-216华电云南红河开远大黑山风电场扩建项目195MW', '云南省大理市宾川县', '浙江贝良', '罗宝山', 'MySE216', '叶根载荷安装', 13, 3, 0.2308, '套号', 'C79YM26B008 C79YM26A009 载荷传感器安装', '工作', '工作', 9, 9, NULL, 'submitted', 'on_time');
INSERT INTO daily_reports (report_date, initial_biz_trip_date, entry_date, project, area, related_party, workers, machine_model, work_content, required_qty, completed_qty, progress_percent, remark, today_work, today_work_type, tomorrow_work_type, biz_trip_days, personal_biz_trip_days, user_id, status, timeliness) VALUES ('2026-06-10', '2026-06-05', '2026-06-04', '明阳国电投巨鹿ipc项目', '河北省邢台市巨鹿县', '浙江贝良', '王腾', 'MySE200', 'ipc故障消缺', 16, 5, 0.3125, '1.上机排查7# 号风机，客户端数据正常，主控未报故障 2.8# 号风机主控报Mx载荷异常预警，上机排查，客户端数据正常，线缆走线没问题，通道对接没问题，让现场导出秒级数据，提供给技术人员分析，需重新标定，现场无风待标定', 'ipc故障排查', '工作', '工作', 5, 6, NULL, 'submitted', 'on_time');
INSERT INTO daily_reports (report_date, initial_biz_trip_date, entry_date, project, area, related_party, workers, machine_model, work_content, required_qty, completed_qty, progress_percent, remark, today_work, today_work_type, tomorrow_work_type, biz_trip_days, personal_biz_trip_days, user_id, status, timeliness) VALUES ('2026-06-10', '2026-06-05', '2026-03-04', 'MySE18-292中广核广东阳江帆石二1000MW一标段【三标段】（中标600MW）', '陆丰市 明阳叶片厂', '浙江贝良，北京拓维', '吴育庆，候明泽', 'MY143', '安装载荷传感器', 0, 0, NULL, 'F11BM26018套号 F11BM26A023编号 F11BM26021套号 F11BM26C004编号', '传感器安装', '工作', '工作', 5, 98, NULL, 'submitted', 'on_time');
INSERT INTO daily_reports (report_date, initial_biz_trip_date, entry_date, project, area, related_party, workers, machine_model, work_content, required_qty, completed_qty, progress_percent, remark, today_work, today_work_type, tomorrow_work_type, biz_trip_days, personal_biz_trip_days, user_id, status, timeliness) VALUES ('2026-06-10', '2026-04-10', '2026-04-10', '安徽亳州蒙城县坛城华润风电场', '安徽省亳州市坛城县', '浙江贝良，甘肃鑫凯', '徐羚译，李智文', 'GW H191/5270（V12）', '叶片载荷，振动传感器消缺', 19, 19, 1.0, '1.大风未作业', '1.根据风况开展作业。', '待工', '工作', 61, 61, NULL, 'submitted', 'on_time');
INSERT INTO daily_reports (report_date, initial_biz_trip_date, entry_date, project, area, related_party, workers, machine_model, work_content, required_qty, completed_qty, progress_percent, remark, today_work, today_work_type, tomorrow_work_type, biz_trip_days, personal_biz_trip_days, user_id, status, timeliness) VALUES ('2026-06-10', '2026-05-19', '2026-03-04', '南非Beta-2项目', '江苏省扬州市扬州港', '浙江贝良、北京拓维', '田子民、孙润耕', 'SI90.2', '叶根载荷+光纤振动安装', 3, 3, 1.0, '1.叶根载荷+振动传感器安装 套号', 'ZC1S190.2A26055 ZC1S190.2D26055 2.北京拓维更替人员已到达阜宁现场', '工作', '在途', 22, 98, NULL, 'submitted', 'on_time');
INSERT INTO daily_reports (report_date, initial_biz_trip_date, entry_date, project, area, related_party, workers, machine_model, work_content, required_qty, completed_qty, progress_percent, remark, today_work, today_work_type, tomorrow_work_type, biz_trip_days, personal_biz_trip_days, user_id, status, timeliness) VALUES ('2026-06-10', '2026-05-26', '2026-03-29', '福建莆田三峡平海湾DE区海上风电场', '福建莆田', '浙江贝良 北京拓维', '仪如招  李鑫', 'GW122', '叶片载荷传感器消缺', 12, 2, 0.1667, '1.大风天气，未安排工作。 2.去项目部开出海班前会。 3.审核安装报告', '15#更换载荷传感器。', '待工', '工作', 15, 73, NULL, 'submitted', 'on_time');
INSERT INTO daily_reports (report_date, initial_biz_trip_date, entry_date, project, area, related_party, workers, machine_model, work_content, required_qty, completed_qty, progress_percent, remark, today_work, today_work_type, tomorrow_work_type, biz_trip_days, personal_biz_trip_days, user_id, status, timeliness) VALUES ('2026-06-10', '2026-05-30', '2026-03-05', '华电贵州黔西南州岩架风电场一期90MW', '贵州省黔西南州', '浙江贝良', '周洁/高裕', '', '激光雷达消缺', 0, 0, NULL, '1.明阳岩架1号风机激光雷达程序升级和角度调整完成。 2.明阳岩架1号风机激光雷达升级后报故障停机处理完成。 3.报告审核，各项目安装升级信息与资料整理。', '1.激光雷达程序升级，安装消缺', '工作', '工作', 11, 97, 9, 'submitted', 'on_time');
INSERT INTO daily_reports (report_date, initial_biz_trip_date, entry_date, project, area, related_party, workers, machine_model, work_content, required_qty, completed_qty, progress_percent, remark, today_work, today_work_type, tomorrow_work_type, biz_trip_days, personal_biz_trip_days, user_id, status, timeliness) VALUES ('2026-06-10', '2026-02-25', '2026-02-24', 'M7-E(10-233)内部客户内蒙古锡林郭勒盟苏尼特左旗风u电治沙项目250MW-25台-锡盟基地', '宁夏自治区中卫市', '浙江贝良', '李余伟', 'MySE233', '叶根载荷安装', 14, 11, 0.7857, '套号D71FM26011 编号D71FM26D016 D71FM26D017', '传感器安装', '工作', '工作', 105, 106, NULL, 'submitted', 'on_time');
INSERT INTO daily_reports (report_date, initial_biz_trip_date, entry_date, project, area, related_party, workers, machine_model, work_content, required_qty, completed_qty, progress_percent, remark, today_work, today_work_type, tomorrow_work_type, biz_trip_days, personal_biz_trip_days, user_id, status, timeliness) VALUES ('2026-06-10', '2026-06-09', '2026-05-20', '承德天润丰宁集中式300.00MW风电场', '河北省承德市丰宁县鱼儿山镇', '浙江贝良', '安义、李自阳（鑫凯）', '93A', '压电消缺', 3, 1, 0.3333, '1.完成17号机组相关工作', '1.开展18号机组相关工作', '', '', 1, 21, NULL, 'submitted', 'on_time');
INSERT INTO daily_reports (report_date, initial_biz_trip_date, entry_date, project, area, related_party, workers, machine_model, work_content, required_qty, completed_qty, progress_percent, remark, today_work, today_work_type, tomorrow_work_type, biz_trip_days, personal_biz_trip_days, user_id, status, timeliness) VALUES ('2026-06-10', '2026-04-08', '2026-02-27', '华电新疆哈密天山北麓基地610万千瓦新能源420万项目标段四60万', '新疆哈密淖毛湖', '浙江贝良，甘肃鑫凯', '薛森虎，张磊磊', 'MySE11D233H125，明阳', '辅控叶片应力模块调试、一台机组IPC主控及辅控安装', 55, 0, 0.0, '1.大风，未作业', '1.IPC辅控调试', '待工', '工作', 63, 103, NULL, 'submitted', 'on_time');
INSERT INTO daily_reports (report_date, initial_biz_trip_date, entry_date, project, area, related_party, workers, machine_model, work_content, required_qty, completed_qty, progress_percent, remark, today_work, today_work_type, tomorrow_work_type, biz_trip_days, personal_biz_trip_days, user_id, status, timeliness) VALUES ('2026-06-10', '2026-05-25', '2026-03-04', '广东湛江市徐闻县东二海上中核风电场', '阳江市平岗镇', '浙江贝良 北京拓维', '韩拥华   张泽源', 'GW122', '安装载荷，振动传感器', 21, 10, 0.4762, 'ZC10SI12226019套号 ZC10SI122D26026编号 ZC10SI122D26027编号 振动', '传感器安装', '工作', '工作', 16, 98, NULL, 'submitted', 'on_time');
INSERT INTO daily_reports (report_date, initial_biz_trip_date, entry_date, project, area, related_party, workers, machine_model, work_content, required_qty, completed_qty, progress_percent, remark, today_work, today_work_type, tomorrow_work_type, biz_trip_days, personal_biz_trip_days, user_id, status, timeliness) VALUES ('2026-06-08', '2026-06-08', '2026-02-27', '新疆塔城地区托里县乌雪特乡天润市场化并网（配套储能）风电场', '新疆省塔城地区', '浙江贝良', '叶丁瑜', 'GW93A', '压电振动跟机消缺', 0, 0, NULL, '办理入场', '叶片振动消缺', '待工', '工作', 0, 101, NULL, 'submitted', 'on_time');
INSERT INTO daily_reports (report_date, initial_biz_trip_date, entry_date, project, area, related_party, workers, machine_model, work_content, required_qty, completed_qty, progress_percent, remark, today_work, today_work_type, tomorrow_work_type, biz_trip_days, personal_biz_trip_days, user_id, status, timeliness) VALUES ('2026-06-09', '2026-06-08', '2026-02-27', '新疆塔城地区托里县乌雪特乡天润市场化并网（配套储能）风电场', '新疆省塔城地区', '浙江贝良', '叶丁瑜', 'GW93A', '压电振动跟机消缺', 0, 0, NULL, '19#机组叶片振动消缺', '叶片振动消缺', '工作', '工作', 1, 102, NULL, 'submitted', 'on_time');
INSERT INTO daily_reports (report_date, initial_biz_trip_date, entry_date, project, area, related_party, workers, machine_model, work_content, required_qty, completed_qty, progress_percent, remark, today_work, today_work_type, tomorrow_work_type, biz_trip_days, personal_biz_trip_days, user_id, status, timeliness) VALUES ('2026-06-10', '2026-06-08', '2026-02-27', '新疆塔城地区托里县乌雪特乡天润市场化并网（配套储能）风电场', '新疆省塔城地区', '浙江贝良', '叶丁瑜', 'GW93A', '压电振动跟机消缺', 0, 0, NULL, '21#机组叶片振动消缺', '乌雪特天润二期提交入场资料', '工作', '待工', 2, 103, NULL, 'submitted', 'on_time');
